// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3Hb9_3LefPRautrDqrZixdcGJyarneI',
    appId: '1:421672729731:web:664bac6a673407e9542fb6',
    messagingSenderId: '421672729731',
    projectId: 'phoneauth-69adf',
    authDomain: 'phoneauth-69adf.firebaseapp.com',
    storageBucket: 'phoneauth-69adf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYWelcoua2UJ9FBk-ccXOKl-HQ_e3Mjo',
    appId: '1:421672729731:android:bbca08703b46f4e1542fb6',
    messagingSenderId: '421672729731',
    projectId: 'phoneauth-69adf',
    storageBucket: 'phoneauth-69adf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOEboEtoGl5dSEEPRtGbKLZ8jyxbLzCb8',
    appId: '1:421672729731:ios:1e01d7560c44c332542fb6',
    messagingSenderId: '421672729731',
    projectId: 'phoneauth-69adf',
    storageBucket: 'phoneauth-69adf.appspot.com',
    iosClientId: '421672729731-aik0vqlvrv6n0kfgcs70k4bnhdu9maki.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOEboEtoGl5dSEEPRtGbKLZ8jyxbLzCb8',
    appId: '1:421672729731:ios:1e01d7560c44c332542fb6',
    messagingSenderId: '421672729731',
    projectId: 'phoneauth-69adf',
    storageBucket: 'phoneauth-69adf.appspot.com',
    iosClientId: '421672729731-aik0vqlvrv6n0kfgcs70k4bnhdu9maki.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginflutter',
  );
}
